version: '3.8'

services:
  flight-status-service:
    image: eurowings/flight-status-service:latest
    mem_limit: 700m
    ports:
      - '8080:8080'
     
  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
                
  kibana:
    image: kibana:7.12.1
    ports:
      - '5601:5601'